### ISSUE TITLE
Feature: mark skip in md file

### ISSUE THREAD

**Issue by Borda** [tmarktaylor/phmdoctest#5]
I found the skipping by counting a bit confusing as each edit in the MD files requires re-count blocks in the test generation command which would be already included in some CI/CD... also having then indexes numerical would be more robust to typos
A better alternative I would see as marking the skip block in the MD file itself, similar as https://github.com/nschloe/exdown does with custom label `<!--exdown-skip-->` see their example:

    Lorem ipsum
    
    ```python
    foo + bar  # not working
    ```
    dolor sit amet.

**Comment by tmarktaylor** [comment]
Rather than putting a Markdown comment `<!-- -->` before the fenced code block for the tool exdown, consider putting the comment in the code block itself.  It can go anywhere. In the example you quoted replace

    # not working

with

    # phmskip since not working

and use the phmdoctest command line option --skip like this: 

    --skip=phmskip

**phmdoctest** will skip this code block no matter where it occurs in the Markdown file. 

The `# phmskip since not working` remains visible in the rendered markdown as reminder that the block is not tested. This works as well for Python interactive sessions.

**Comment by Borda** [comment]
well then you can rather think about annotating lines similar to doctest, so particular lines would not be included in the test at all, and the extreme case would be skiping all in the particular example...

**Comment by tmarktaylor** [comment]
Consider putting the line `<!-- phmdoctest skip -->` on the line immediately before `<!--exdown-skip-->` in the example in the first post to this issue conversation. **phmdoctest** would see the HTML comment and not generate a test case for the Markdown fenced code block.

Let's call it a *phmdoctest directive* since it is similar to a Python doctest directive. It is used to modify how **phmdoctest** handes a Python syntax highlighted fenced code block.

To rephrase the previous post, I think the aim is to prevent execution of some, but not all, lines in the Python fenced code block.

Readers are invited to propose a **phmdoctest** directive to do this. There is no limit on the number of directives or repetition of a directive. There is no limit to the length of text inside the HTML comment.

Terse, consise, and general purpose directives would be preferred.

Here is a suggestion to stimulate thought: `<!-- phmdoctest skip-someof CRITERIA -->`.

**Comment by tmarktaylor** [comment]
I took a look at some of the files related to testing README.md in the context of  https://github.com/PyTorchLightning/metrics/pull/140.

- In the actions history in https://github.com/PyTorchLightning/metrics/commit/de8ff12565769bdbdf4d98711c84c3236adcae70#diff-cdd65a42e92eea9af640e28f9cfeb07f6c167b0890f17bc2751313d4355333be I found the line `tests/test_readme.py::test_code_125 FAILED` from 24 days ago.

I think this failure occurs when running test_readme.py generated by this command in ci_test_full.yml.

I am quoting it here.
```yml
name: Tests
      run: |
        phmdoctest README.md --outfile tests/test_readme.py
        python -m pytest torchmetrics tests -v --cov=torchmetrics --junitxml=junit/test-results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}.xml
```

Try the following phmdoctest command instead.

```yml
phmdoctest README.md --skip=metric_dpp --outfile tests/test_readme.py
```

Please double check that no other fenced code blocks that need to be tested have the string metric_dpp.

I also noticed that phmdoctest is dicovering fenced code blocks within `<details>` but only if the opening `<details>` is followed by a blank line. This looks strange.

Your suggestion has prompted me to start working on an update with 7 new directives including a `<!--phmdoctest-skip-->` directive.  A reasonable guess would v1.1.0 hits PYPI in 2-6 weeks. Nothing in v1.1.0 will resemble 
the `skip-someof` suggestion in my last comment.

**Comment by Borda** [comment]
@tmarktaylor great for adding this feature!
just testing it but seems not to be work for me, what am doing wrong?
https://github.com/PyTorchLightning/metrics/pull/140/files

**Comment by tmarktaylor** [comment]
@Borda said above > well then you can rather think about annotating lines similar to doctest, so particular lines would not be included in the test at all, ...

Reopening this issue to add the feature request quoted above.
